# Generated by Django 6.0.3 on 2026-03-07 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellido')),
                ('date_birth', models.DateField(verbose_name='Fecha de nacimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schedule.person')),
            ],
            bases=('schedule.person',),
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schedule.person')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schedule.specialty')),
            ],
            bases=('schedule.person',),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_appt', models.DateTimeField()),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reason', to='schedule.specialty', verbose_name='Motivo')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient', to='schedule.patient', verbose_name='Paciente')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider', to='schedule.provider', verbose_name='Especialista')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('provider', 'datetime_appt'), name='unique_appointment')],
            },
        ),
    ]
