# Generated by Django 6.0.3 on 2026-03-07 21:18

from django.db import migrations


def create_specialties(apps, schema_editor):
    Specialty = apps.get_model("schedule", "Specialty")

    specialties = [
        "Medicina general",
        "Cardiología",
        "Pediátrica",
        "Cirugía",
        "Dermatología",
        "Obstetricia Ginecología",
        "Otorrinolaringología",
        "Gastroenterología",
    ]

    for name in specialties:
        Specialty.objects.get_or_create(name=name)

class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_specialties)
    ]
