# Generated by Django 6.0.3 on 2026-03-17 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20260307_1920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'cita', 'verbose_name_plural': 'citas'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'paciente', 'verbose_name_plural': 'pacientes'},
        ),
        migrations.AlterModelOptions(
            name='provider',
            options={'verbose_name': 'doctor', 'verbose_name_plural': 'doctores'},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='datetime_appt',
            field=models.DateTimeField(verbose_name='Cita'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schedule.specialty', verbose_name='Especialidad'),
        ),
    ]
